/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.RegistroProdutosController;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author NEX
 */
public class RegistroProdutos extends javax.swing.JFrame {

    private static boolean aberto = false;

    private final RegistroProdutosController controller;

    TelaPrincipal TP = new TelaPrincipal();
    
    
    public RegistroProdutos() {
        initComponents();
        
        if (TP.getTema() == true) {

            label_fundo_RF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/I_Fundos/plano_de_fundo_branco_registro_3.png")));

        } else if (TP.getTema() == false) {

            label_fundo_RF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/I_Fundos/plano_de_fundo_preto_registro_3.png")));
        }

        controller = new RegistroProdutosController(this);

        //Caso feche pelas Abas não da erro!
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                aberto = false;
                dispose();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_Fundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateFerramenta = new javax.swing.JButton();
        jBotaoCadastroFerramenta = new javax.swing.JButton();
        jDeleteFerramenta = new javax.swing.JButton();
        b_voltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        txtnomeFerramenta = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        labelFone1 = new javax.swing.JLabel();
        labelFone = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        label_fundo_RF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        JP_Fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(8, 119, 197));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(335, 39));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateFerramenta.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        updateFerramenta.setText("Atualizar");
        updateFerramenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateFerramenta.setFocusPainted(false);
        updateFerramenta.setVisible(false);
        updateFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFerramentaActionPerformed(evt);
            }
        });
        jPanel2.add(updateFerramenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, -1));

        jBotaoCadastroFerramenta.setVisible(false);
        jBotaoCadastroFerramenta.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBotaoCadastroFerramenta.setText("Cadastrar");
        jBotaoCadastroFerramenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotaoCadastroFerramenta.setFocusPainted(false);
        jBotaoCadastroFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoCadastroFerramentaActionPerformed(evt);
            }
        });
        jPanel2.add(jBotaoCadastroFerramenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, -1));

        setVisible(false);
        jDeleteFerramenta.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jDeleteFerramenta.setText("Delete");
        jDeleteFerramenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDeleteFerramenta.setFocusPainted(false);
        jDeleteFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteFerramentaActionPerformed(evt);
            }
        });
        jPanel2.add(jDeleteFerramenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, -1));

        b_voltar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        b_voltar.setText("Voltar");
        b_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_voltar.setFocusPainted(false);
        b_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_voltarActionPerformed(evt);
            }
        });
        jPanel2.add(b_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 120, -1));

        JP_Fundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 440, 47));

        jPanel1.setBackground(new java.awt.Color(235, 120, 3));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(469, 177));

        labelNome.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelNome.setText("Nome:");

        txtnomeFerramenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomeFerramentaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomeFerramentaFocusLost(evt);
            }
        });
        txtnomeFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeFerramentaActionPerformed(evt);
            }
        });
        txtnomeFerramenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeFerramentaKeyPressed(evt);
            }
        });

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelEmail.setText("Marca:");

        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyReleased(evt);
            }
        });

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });

        labelFone1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelFone1.setText("Quantidade:");

        labelFone.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelFone.setText("Preço:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFone1)
                    .addComponent(labelFone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtnomeFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomeFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFone))
                .addContainerGap())
        );

        JP_Fundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 440, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JP_Fundo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 385));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        JP_Fundo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 5));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        JP_Fundo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 0, 5, 385));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        JP_Fundo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 385, 890, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produtos");
        JP_Fundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 440, 50));

        txtId.setVisible(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        JP_Fundo.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, -1));

        label_fundo_RF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/I_Fundos/plano_de_fundo_branco_registro_3.png"))); // NOI18N
        JP_Fundo.add(label_fundo_RF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean isAberto() {
        return aberto;
    }

    public void setAberto(boolean aberto) {
        this.aberto = aberto;
    }


    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void jBotaoCadastroFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoCadastroFerramentaActionPerformed
        controller.registrarProduto();
        this.principalAxu.getListaClientesProdutosController().listarProdutos();
        
    }//GEN-LAST:event_jBotaoCadastroFerramentaActionPerformed

    private void updateFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFerramentaActionPerformed
        String textoFerramenta = txtnomeFerramenta.getText();
        boolean numero = Util.Util.verficarNumnoTexto(textoFerramenta);

        if (numero) {
            controller.updateProduto();
            aberto = false;
            dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Campo nome não recebe números");
        }


    }//GEN-LAST:event_updateFerramentaActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jDeleteFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteFerramentaActionPerformed
        controller.deleteProduto();
        JOptionPane.showMessageDialog(null, "Produto deletado com sucesso!");
        aberto = false;
        dispose();
    }//GEN-LAST:event_jDeleteFerramentaActionPerformed

    private void b_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_voltarActionPerformed
        aberto = false;
        dispose();
    }//GEN-LAST:event_b_voltarActionPerformed

    private void txtnomeFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeFerramentaActionPerformed

    private void txtnomeFerramentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeFerramentaKeyPressed

    }//GEN-LAST:event_txtnomeFerramentaKeyPressed

    private void txtnomeFerramentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFerramentaFocusLost
        validarCampos();
    }//GEN-LAST:event_txtnomeFerramentaFocusLost

    private void txtnomeFerramentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFerramentaFocusGained

    }//GEN-LAST:event_txtnomeFerramentaFocusGained

    private void jFormattedTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyReleased
        String texto = jFormattedTextField1.getText().replaceAll("[^\\d]", ""); // Remover todos os caracteres não numéricos
        if (texto.isEmpty()) {
            jFormattedTextField1.setText("0");
            return;
        }

        try {
            long valor = Long.parseLong(texto);
            NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance();
            jFormattedTextField1.setText(formatoMoeda.format(valor / 100.0)); // Converter centavos em reais
        } catch (NumberFormatException ex) {
            // Lidar com exceção se a entrada não puder ser convertida em número
            jFormattedTextField1.setText("0");
        }
    }//GEN-LAST:event_jFormattedTextField1KeyReleased

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
             char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
        evt.consume();
    }
        }//GEN-LAST:event_txtQuantidadeKeyTyped

    public boolean isNumeric(String input, Pattern pattern) {
        Matcher matcher = pattern.matcher(input);
        return matcher.matches();
    }

    public static String extractNumbers(String input) {
        StringBuilder numbers = new StringBuilder();
        Pattern pattern = Pattern.compile("\\d+");
        Matcher matcher = pattern.matcher(input);

        while (matcher.find()) {
            numbers.append(matcher.group());
        }

        return numbers.toString();
    }


    //  System.out.println(currencyFormatter.format(funcionario.salario));
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroProdutos.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroProdutos.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroProdutos.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroProdutos.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_Fundo;
    private javax.swing.JButton b_voltar;
    private javax.swing.JButton jBotaoCadastroFerramenta;
    private javax.swing.JButton jDeleteFerramenta;
    private javax.swing.JTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFone;
    private javax.swing.JLabel labelFone1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel label_fundo_RF;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtnomeFerramenta;
    private javax.swing.JButton updateFerramenta;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtMarca() {
        return txtMarca;
    }

    public void setTxtMarca(JTextField txtMarca) {
        this.txtMarca = txtMarca;
    }

    public JTextField getjFormattedTextField1() {
        return jFormattedTextField1;
    }

    public void setjFormattedTextField1(JTextField jFormattedTextField1) {
        this.jFormattedTextField1 = jFormattedTextField1;
    }

    public JTextField getTxtQuantidade() {
        return txtQuantidade;
    }

    public void setTxtQuantidade(JTextField txtQuantidade) {
        this.txtQuantidade = txtQuantidade;
    }

    public JTextField getTxtnomeFerramenta() {
        return txtnomeFerramenta;
    }

    public void setTxtnomeFerramenta(JTextField txtnomeFerramenta) {
        this.txtnomeFerramenta = txtnomeFerramenta;
    }

    public JButton getjBotaoCadastroFerramenta() {
        return jBotaoCadastroFerramenta;
    }

    public void setjBotaoCadastroFerramenta(JButton jBotaoCadastroFerramenta) {
        this.jBotaoCadastroFerramenta = jBotaoCadastroFerramenta;
    }

    public JButton getjDeleteFerramenta() {
        return jDeleteFerramenta;
    }

    public void setjDeleteFerramenta(JButton jDeleteFerramenta) {
        this.jDeleteFerramenta = jDeleteFerramenta;
    }

    public JButton getUpdateFerramenta() {
        return updateFerramenta;
    }

    public void setUpdateFerramenta(JButton updateFerramenta) {
        this.updateFerramenta = updateFerramenta;
    }

    
    
    
    public void validarCampos() {
        String textoFerramenta = txtnomeFerramenta.getText();
        boolean numero = Util.Util.verficarNumnoTexto(textoFerramenta);
        updateFerramenta.setEnabled(numero);
        jBotaoCadastroFerramenta.setEnabled(numero);
        if (!numero) {

            JOptionPane.showMessageDialog(null, "Este campo não números");

        }

    }
    
    
    private TelaPrincipal principalAxu;
    public void setPrincipal(TelaPrincipal principal){
        this.principalAxu = principal;
    
    }
}
